---
title: "HMDB cookbook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

## Merge database

```{r}
# refmet
refmet <- read.csv("refmet/refmet.csv")
# hmdb
hmdbnew <- read.csv("hmdb/hmdb.csv")
# t3db
t3dbnew <- read.csv("t3db/t3dbnew.csv")
# foodb
foodb <- read.csv("foodb/Compound.csv")
foodb$InChIKey <- gsub( "InChIKey=", "", as.character(foodb$moldb_inchikey))
foodbnew <- foodb[!duplicated(foodb$moldb_smiles),]
# dsstox
dsstox <- read.csv("dsstox/dsstox.csv")
# chebi
chebi <- read.csv("chebi/chebi.csv")
# drugbank
# drugbank <- read.csv("drugbank/drugbank.csv")
# drugbank$InChIKey <- drugbank$`Standard InChI Key`
# drugbanknew <- drugbank[!duplicated(drugbank$InChIKey),]
HMDB <- cbind.data.frame(hmdb = hmdbnew$accession,inchikey = hmdbnew$InChIKey)
HMDB <- HMDB[complete.cases(HMDB),]
dsstox <- cbind.data.frame(dsstox = dsstox$DTXSID,inchikey = dsstox$inchikey)
dsstox <- dsstox[complete.cases(dsstox),]
dsstox <- dsstox[stringi::stri_length(dsstox$inchikey)>0,]
t3db <- cbind.data.frame(t3db = t3dbnew$accession,inchikey = t3dbnew$InChIKey)
t3db <- t3db[complete.cases(t3db),]
foodb <- cbind.data.frame(foodb = foodbnew$public_id,inchikey = foodbnew$moldb_smiles)
foodb <- foodb[complete.cases(foodb),]
foodb <- foodb[stringi::stri_length(foodb$inchikey)>0,]
refmet <- cbind.data.frame(refmet = refmet$refmet_name,inchikey = refmet$inchi_key)
refmet <- refmet[complete.cases(refmet),]
refmet <- refmet[stringi::stri_length(refmet$inchikey)>0,]
chebi <- cbind.data.frame(chebi = chebi$CHEBI_ID,inchikey = chebi$inchikey)
chebi <- chebi[complete.cases(chebi),]
chebi <- chebi[stringi::stri_length(chebi$inchikey)>0,]
all <- list(HMDB, dsstox, t3db, foodb, refmet, chebi)
alldf <- Reduce(function(x, y) merge(x, y, all=TRUE,by = 'inchikey'), all)
write.csv(alldf,'alldf.csv')
all <- list(HMDB = HMDB$inchikey, dsstox = dsstox$inchikey, t3db=t3db$inchikey, foodb=foodb$inchikey, refmet = refmet$inchikey, chebi = chebi$inchikey)
library(UpSetR)
upset(fromList(all), order.by = "freq")
```

## Search MS2 precursor

```{r}
db <- read.csv('alldf.csv')
posdb <- read.csv('posdb.csv')
length(unique(posdb$inchikey))
negdb <- read.csv('negdb.csv')
length(unique(negdb$inchikey))
dbid <- merge(posdb,db,by = 'inchikey')
inchikey <- paste(dbid$inchikey,round(dbid$precursorMz,3))
dbid <- dbid[!duplicated(inchikey)&!is.na(dbid$precursorMz)&!is.na(dbid$inchikey),]
length(unique(dbid$inchikey))
write.csv(dbid[,-c(2,7)],'allms2pos.csv')
dbid <- merge(negdb,db,by = 'inchikey')
inchikey <- paste(dbid$inchikey,round(dbid$precursorMz,3))
dbid <- dbid[!duplicated(inchikey)&!is.na(dbid$precursorMz)&!is.na(dbid$inchikey),]
length(unique(dbid$inchikey))
write.csv(dbid[,-c(2,7)],'allms2neg.csv')
```

## Search

```{r}
hr <- readRDS('hmdbrefmet.RDS')
add <- c('Na-H','H','NH4')
pmd <- unlist(Map(enviGCMS::getmass,add))
pmdm <- outer(hr$mass,pmd,'+')
rownames(pmdm) <- hr$name
mz2 <- c(282.279, 281.113, 227.139, 227.139, 302.207)
re <- enviGCMS::getalign(pmdm[,1],mz2)
re2 <- hr[re$xid,]
re3 <- cbind.data.frame(re[,-1],re2)
colnames(re3)[1] <- add[1]

mz2 <- c(282.279, 281.113, 227.139, 227.139, 302.207)

getms1anno <- function(pmd,mz,ppm=10){
    # hr <- get(hr)
    if(is.character(pmd)){
        pmds <- unlist(Map(enviGCMS::getmass,pmd))
    }else{
        pmds <- pmd
    }
    
    if(length(pmd)>1){
        pmdmt <- outer(hr$mass,pmds,'+')
        rownames(pmdmt) <- hr$name
        li <- list()
    for(i in 1:length(pmd)){
        re <- enviGCMS::getalign(pmdmt[,i],mz,ppm = ppm)
        re2 <- hr[re$xid,]
        re3 <- cbind.data.frame(re[,-1],re2)
        colnames(re3)[1] <- pmd[i]
        li[[i]] <- re3
        }
        return(li)
    }else{
        pmdmt <- outer(hr$mass,pmds,'+')
        rownames(pmdmt) <- hr$name
        re <- enviGCMS::getalign(pmdmt,mz,ppm = ppm)
        re2 <- hr[re$xid,]
        re3 <- cbind.data.frame(re[,-1],re2)
        colnames(re3)[1] <- pmd
        return(re3)
    }
} 

z <- getms1anno(c('Na-H','H','NH4'),c(282.279, 281.113, 227.139, 227.139, 302.207),ppm = 5)

library(readr)
cts_teeth <- read_csv("cts-20181101112732.csv")
hmdbnew <- read.csv("hmdb/hmdb.csv",stringsAsFactors = F)

sum(cts_teeth$InChIKey %in% hmdbnew$InChIKey)

teeth <- merge(cts_teeth,hmdbnew,by = 'InChIKey')
tar <- read.csv("../test/classtar.csv",stringsAsFactors = F)
teeth <- merge(tar,hmdbnew,by.x = 'smilesall',by.y = 'smiles')
```

## classification

```{r}
classyfireR::get_classification(InChIKey)
```

## disease

```{r}
dname <- read.csv('hmdb/hmdbdname.csv')
```

## chebi

```{r}
library(reticulate)
use_python("/opt/homebrew/bin/python3")
```

```{python}
import pandas as pd
import rdkit
from rdkit import Chem

chebi = pd.read_table("chebi/chebiId_inchi_3star.tsv")
inchikey = []
for i in chebi.InChI:
    try:
        mol = Chem.MolFromInchi(i)
        it = str(Chem.MolToInchiKey(mol))
    except:
        it = None
    inchikey.append(it)
    
chebi = chebi.assign(inchikey = inchikey)
chebi.to_csv('chebi/chebi.csv')
```

## dsstox

```{r}
dss <- read.table('dsstox/dsstox_20160701.tsv',header = F)
colnames(dss) <- c('DTXSID','inchi','inchikey')
write.csv(dss[,-2],'dsstox/dsstox.csv')
```


## mzCloud

```{python}
from bs4 import BeautifulSoup
import time
inchi = []
id = []
for x in range(1,11570):
webpage = "https://www.mzcloud.org/compound/reference/" + str(x)
page = requests.get(webpage)
soup = BeautifulSoup(page.content,"html.parser")
results = soup.select("body > div > div:nth-child(7) > div > div > table")
inchi.append(results[0].find_all('td')[3].string)
id.append(x)
time.sleep(0.1)
import pandas as pd
re = pd.DataFrame({'id': id, 'inchikey': inchi})
re.to_csv('mzcloud.csv')
```

