---
title: "HMDB"
output: html_document
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python('/usr/local/bin/python3')
```

## Convert the xml files into csv files

### Bash Code

```{bash}
xmlstarlet sel -N hmdb=http://www.hmdb.ca -T -t -m //hmdb:metabolite -v "concat(//hmdb:metabolite//hmdb:accession,',',//hmdb:metabolite//hmdb:monisotopic_molecular_weight,',',//hmdb:metabolite//hmdb:iupac_name,',',//hmdb:metabolite//hmdb:name,',',//hmdb:metabolite//hmdb:chemical_formula,',',//hmdb:metabolite//hmdb:cas_registry_number,',',//hmdb:metabolite//hmdb:smiles,',',//hmdb:metabolite//hmdb:kingdom,',',//hmdb:metabolite//hmdb:direct_parent,',',//hmdb:metabolite//hmdb:taxonomy//hmdb:super_class,',',//hmdb:metabolite//hmdb:taxonomy//hmdb:class,',',//hmdb:metabolite//hmdb:taxonomy//hmdb:sub_class, ',',//hmdb:metabolite//hmdb:taxonomy//hmdb:molecular_framework)" -n hmdb_metabolites.xml > hmdb.csv
```

### python Code

```{python}
from io import StringIO
from lxml import etree
import csv
def hmdbextract(name, file):
  ns = {'hmdb': 'http://www.hmdb.ca'}
  context = etree.iterparse(name, tag='{http://www.hmdb.ca}metabolite')
  csvfile = open(file, 'w')
  fieldnames = ['accession', 'monisotopic_molecular_weight', 'iupac_name', 'name', 'chemical_formula', 'InChIKey', 'cas_registry_number', 'smiles', 'drugbank','chebi_id', 'pubchem', 'phenol_explorer_compound_id','food','knapsack', 'chemspider', 'kegg', 'meta_cyc','bigg','metlin_id','pdb_id', 'logpexp','kingdom',  'direct_parent', 'super_class', 'class', 'sub_class', 'molecular_framework']
  writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
  writer.writeheader()
  for event, elem in context:

    accession = elem.xpath('hmdb:accession/text()', namespaces=ns)[0]
    try:
        monisotopic_molecular_weight = elem.xpath('hmdb:monisotopic_molecular_weight/text()', namespaces=ns)[0]
    except:
        monisotopic_molecular_weight = 'NA'
    try:
        iupac_name = elem.xpath('hmdb:iupac_name/text()', namespaces=ns)[0].encode('utf-8')
    except:
        iupac_name = 'NA'
    name = elem.xpath('hmdb:name/text()', namespaces=ns)[0].encode('utf-8')
    try:
        chemical_formula = elem.xpath('hmdb:chemical_formula/text()', namespaces=ns)[0]
    except:
        chemical_formula = 'NA'
    try:
        inchikey = elem.xpath('hmdb:inchikey/text()', namespaces=ns)[0]
    except:
        inchikey = 'NA'
    try:
        cas_registry_number = elem.xpath('hmdb:cas_registry_number/text()', namespaces=ns)[0]
    except:
        cas_registry_number = 'NA'
    try:
        smiles = elem.xpath('hmdb:smiles/text()', namespaces=ns)[0]
    except:
        smiles = 'NA'
    try:
        drugbank = elem.xpath('hmdb:drugbank_id/text()', namespaces=ns)[0]
    except:
        drugbank = 'NA'
    try:
        chebi_id = elem.xpath('hmdb:chebi_id/text()', namespaces=ns)[0]
    except:
        chebi_id = 'NA'
    try:
        pubchem = elem.xpath('hmdb:pubchem_compound_id/text()', namespaces=ns)[0]
    except:
        pubchem = 'NA'
    try:
        phenol_explorer_compound_idt = elem.xpath('hmdb:phenol_explorer_compound_id/text()', namespaces=ns)[0]
    except:
        phenol_explorer_compound_id = 'NA'
    try:
        food = elem.xpath('hmdb:foodb_id/text()', namespaces=ns)[0]
    except:
        food = 'NA'
    try:
        knapsack = elem.xpath('hmdb:knapsack_id/text()', namespaces=ns)[0]
    except:
        knapsack = 'NA'
    try:
        chemspider = elem.xpath('hmdb:chemspider_id/text()', namespaces=ns)[0]
    except:
        chemspider = 'NA'
    try:
        kegg = elem.xpath('hmdb:kegg_id/text()', namespaces=ns)[0]
    except:
        kegg = 'NA'
    try:
        meta_cyc = elem.xpath('hmdb:meta_cyc_id/text()', namespaces=ns)[0]
    except:
        meta_cyc = 'NA'
    try:
        bigg = elem.xpath('hmdb:bigg_id/text()', namespaces=ns)[0]
    except:
        bigg = 'NA'
    try:
        metlin_id = elem.xpath('hmdb:metlin_id/text()', namespaces=ns)[0]
    except:
        metlin_id = 'NA'
    try:
        pdb_id = elem.xpath('hmdb:pdb_id/text()', namespaces=ns)[0]
    except:
        pdb_id = 'NA'
    try:
        logpexp = elem.xpath('hmdb:experimental_properties/hmdb:property[hmdb:kind = "logp"]/hmdb:value/text()', namespaces=ns)[0]
    except:
        logpexp = 'NA'
    try:
        kingdom = elem.xpath('hmdb:taxonomy/hmdb:kingdom/text()', namespaces=ns)[0]
    except:
        kingdom = 'NA'
    try:
        direct_parent = elem.xpath('hmdb:taxonomy/hmdb:direct_parent/text()', namespaces=ns)[0]
    except:
        direct_parent = 'NA'
    try:
        super_class = elem.xpath('hmdb:taxonomy/hmdb:super_class/text()', namespaces=ns)[0]
    except:
        super_class = 'NA'
    try:
        classorg = elem.xpath('hmdb:taxonomy/hmdb:class/text()', namespaces=ns)[0]
    except:
        classorg = 'NA'
    try:
        sub_class = elem.xpath('hmdb:taxonomy/hmdb:sub_class/text()', namespaces=ns)[0]
    except:
        sub_class = 'NA'
    try:
        molecular_framework = elem.xpath('hmdb:taxonomy/hmdb:molecular_framework/text()', namespaces=ns)[0]
    except:
        molecular_framework = 'NA'

    writer.writerow({'accession': accession, 'monisotopic_molecular_weight': monisotopic_molecular_weight, 'iupac_name': iupac_name, 'name': name, 'chemical_formula': chemical_formula, 'InChIKey': inchikey, 'cas_registry_number': cas_registry_number, 'smiles': smiles,'drugbank': drugbank,'chebi_id': chebi_id,'pubchem': pubchem,'phenol_explorer_compound_id':phenol_explorer_compound_id, 'food': food,'knapsack': knapsack, 'chemspider': chemspider,'kegg': kegg, 'meta_cyc': meta_cyc, 'bigg':bigg, 'metlin_id': metlin_id, 'pdb_id':pdb_id,'logpexp':logpexp, 'kingdom': kingdom, 'direct_parent': direct_parent, 'super_class': super_class, 'class': classorg, 'sub_class': sub_class, 'molecular_framework': molecular_framework})
    # It's safe to call clear() here because no descendants will be
    # accessed
    elem.clear()
# Also eliminate now-empty references from the root node to elem
    for ancestor in elem.xpath('ancestor-or-self::*'):
        while ancestor.getprevious() is not None:
            del ancestor.getparent()[0]
  del context
  return;
```

```{python pathway}
from io import StringIO
from lxml import etree
import csv
def hmdbpextract(name, file):
  ns = {'hmdb': 'http://www.hmdb.ca'}
  context = etree.iterparse(name, tag='{http://www.hmdb.ca}metabolite')
  csvfile = open(file, 'w')
  fieldnames = ['accession', 'omim', 'dname', 'smpdb', 'keggmap', 'loc', 'protein', 'uniprot', 'gene', 'protein_type']
  writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
  writer.writeheader()
  for event, elem in context:

    accession = elem.xpath('hmdb:accession/text()', namespaces=ns)[0]
    try:
        omim = elem.xpath('hmdb:diseases/hmdb:disease/hmdb:omim_id/text()', namespaces=ns)
    except:
        omim = 'NA'
    try:
        dname = elem.xpath('hmdb:diseases/hmdb:disease/hmdb:name/text()', namespaces=ns)
    except:
        dname = 'NA'
    try:
        smpdb = elem.xpath('hmdb:biological_properties/hmdb:pathways/hmdb:pathway/hmdb:smpdb_id/text()', namespaces=ns)
    except:
        smpdb = 'NA'
    try:
        keggmap = elem.xpath('hmdb:biological_properties/hmdb:pathways/hmdb:pathway/hmdb:kegg_map_id/text()', namespaces=ns)
    except:
        keggmap = 'NA'
    try:
        loc = elem.xpath('hmdb:biological_properties/hmdb:biospecimen_locations/hmdb:biospecimen/text()', namespaces=ns)
    except:
        loc = 'NA'
    try:
        protein = elem.xpath('hmdb:protein_associations/hmdb:protein/hmdb:protein_accession/text()', namespaces=ns)
    except:
        protein = 'NA'    
    try:
        uniprot = elem.xpath('hmdb:protein_associations/hmdb:protein/hmdb:uniprot_id/text()', namespaces=ns)
    except:
        uniprot = 'NA'
    try:
        gene = elem.xpath('hmdb:protein_associations/hmdb:protein/hmdb:gene_name/text()', namespaces=ns)
    except:
        gene = 'NA'
    try:
        protein_type = elem.xpath('hmdb:protein_associations/hmdb:protein/hmdb:protein_type/text()', namespaces=ns)
    except:
        protein_type = 'NA'    
    writer.writerow({'accession': accession, 'omim': omim, 'dname': dname, 'smpdb': smpdb, 'keggmap': keggmap,'loc': loc, 'protein':protein, 'uniprot': uniprot, 'gene': gene, 'protein_type':protein_type })
    # It's safe to call clear() here because no descendants will be
    # accessed
    elem.clear()
# Also eliminate now-empty references from the root node to elem
    for ancestor in elem.xpath('ancestor-or-self::*'):
        while ancestor.getprevious() is not None:
            del ancestor.getparent()[0]
  del context
  return;
```


## HMDB

```{python}
hmdbextract('hmdb_metabolites.xml','hmdb.csv')
hmdbpextract('hmdb_metabolites.xml','hmdbpathway.csv')
```

### parts

```{python}
import os
os.getcwd()
hmdbextract('serum_metabolites.xml','serumhmdb.csv')
hmdbpextract('serum_metabolites.xml','serumhmdb.csv')
hmdbextract('hmdb/urine_metabolites.xml','hmdb/urinehmdb.csv')

hmdbextract('hmdb/csf_metabolites.xml','hmdb/csfhmdb.csv')
hmdbextract('hmdb/feces_metabolites.xml','hmdb/feceshmdb.csv')
hmdbextract('hmdb/saliva_metabolites.xml','hmdb/salivahmdb.csv')
hmdbextract('hmdb/sweat_metabolites.xml','hmdb/sweathmdb.csv')
```

### data clean

```{r anno}
hmdb <- read.csv('hmdb.csv')
hmdb <- read.csv('hmdb/serumhmdb.csv')
hmdb$iupac_name <- gsub( "b'|'$", "", as.character(hmdb$iupac_name))
hmdb$name <- gsub( "b'|'$", "", as.character(hmdb$name))
write.csv(hmdb,'hmdb/serumhmdb.csv')
hmdb <- read.csv('hmdb/salivahmdb.csv')
hmdb$iupac_name <- gsub( "b'|'$", "", as.character(hmdb$iupac_name))
hmdb$name <- gsub( "b'|'$", "", as.character(hmdb$name))
write.csv(hmdb,'hmdb/salivahmdb.csv')
hmdb <- read.csv('hmdb/urinehmdb.csv')
hmdb$iupac_name <- gsub( "b'|'$", "", as.character(hmdb$iupac_name))
hmdb$name <- gsub( "b'|'$", "", as.character(hmdb$name))
write.csv(hmdb,'hmdb/urinehmdb.csv')
hmdb <- read.csv('hmdb/csfhmdb.csv')
hmdb$iupac_name <- gsub( "b'|'$", "", as.character(hmdb$iupac_name))
hmdb$name <- gsub( "b'|'$", "", as.character(hmdb$name))
write.csv(hmdb,'hmdb/csfhmdb.csv')
hmdb <- read.csv('hmdb/sweathmdb.csv')
hmdb$iupac_name <- gsub( "b'|'$", "", as.character(hmdb$iupac_name))
hmdb$name <- gsub( "b'|'$", "", as.character(hmdb$name))
write.csv(hmdb,'hmdb/sweathmdb.csv')
```

### Pathway

```{r}
hmdb <- read.csv('hmdb/hmdbpathway.csv')
hmdb2 <- t(apply(hmdb,1,function(x) gsub( "^\\[|]$", "", as.character(x))))
hmdb2 <- as.data.frame(hmdb2)
colnames(hmdb2) <- colnames(hmdb)

disease <- hmdb2[,c("accession","omim","dname")]

g <- strsplit(as.character(hmdb2$omim), ",")
omim <- data.frame(accession = rep(hmdb2$accession, lapply(g, length)), omimid = unlist(g))
omim$omimid <- as.numeric(gsub( "'| ", "", as.character(omim$omimid)))


g <- strsplit(as.character(hmdb2$dname), ",")
dname <- data.frame(accession = rep(hmdb2$accession, lapply(g, length)), dname = unlist(g))
dname$dname <- gsub( '^ ', "", as.character(dname$dname))
dname$dname <- gsub( "^'|'$", "", as.character(dname$dname))
dname$dname <- gsub( '^"|"$', "", as.character(dname$dname))

g <- strsplit(as.character(hmdb2$protein), ",")
protein <- data.frame(accession = rep(hmdb2$accession, lapply(g, length)), protein = unlist(g))
protein$protein <- gsub( "'| ", "", as.character(protein$protein))

g <- strsplit(as.character(hmdb2$smpdb), ",")
smpdb <- data.frame(accession = rep(hmdb$accession, lapply(g, length)), smpdb = unlist(g))
smpdb$smpdb <- gsub( "'| ", "", as.character(smpdb$smpdb))

g <- strsplit(as.character(hmdb2$keggmap), ",")
keggmap <- data.frame(accession = rep(hmdb$accession, lapply(g, length)), keggmap = unlist(g))
keggmap$keggmap <- gsub( "'| ", "", as.character(keggmap$keggmap))

g <- strsplit(as.character(hmdb2$uniprot), ",")
uniprot <- data.frame(accession = rep(hmdb$accession, lapply(g, length)), uniprot = unlist(g))
uniprot$uniprot <- gsub( "'| ", "", as.character(uniprot$uniprot))

g <- strsplit(as.character(hmdb2$gene), ",")
gene <- data.frame(accession = rep(hmdb$accession, lapply(g, length)), gene = unlist(g))
gene$gene <- gsub( "'| ", "", as.character(gene$gene))

g <- strsplit(as.character(hmdb2$protein_type), ",")
protein_type <- data.frame(accession = rep(hmdb$accession, lapply(g, length)), protein_type = unlist(g))
protein_type$protein_type <- gsub( "'| ", "", as.character(protein_type$protein_type))

write.csv(omim,file = 'hmdbomim.csv')
write.csv(dname,file = 'hmdbdname.csv')
write.csv(protein,file = 'hmdbprotein.csv')
write.csv(smpdb,file = 'hmdbsmpdb.csv')
write.csv(keggmap,file = 'hmdbkeggmap.csv')
write.csv(uniprot,file = 'hmdbuniprot.csv')
write.csv(gene,file = 'hmdbgene.csv')
write.csv(protein_type,file = 'hmdbprotein_type.csv')
```
